# Generated by Django 5.0.2 on 2024-11-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0005_rename_created_at_order_order_date_order_car_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
